# reference: http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11?answertab=active#tab-top

sudo: false
language: cpp
compiler:
    - clang++
    - g++

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then export CXXFLAGS="-std=c++11"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.4
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.4"; fi

  - ls /usr/bin/clang*
  - ls /usr/bin/g++*
  - g++ --version
  - clang++ --version

  - cd ${TRAVIS_BUILD_DIR}
  - ls
  - make CXXFLAGS="${CXXFLAGS}" CXX="${CXX}"
  - ls

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-4.8
#    - g++-4.8
#    - clang++-3.4

script:
  - chmod ugo+x test
  - ./test
